#include<cufft.h>
#include<curand.h>
#include"../include/datamain.th"
#include"tensorb.h"
#include"gtensorb.h"
#include"random.h"
#include"variable.h"

#include"dynamics.h"
/////////////////////////////
//GS_SYS_DEFINE_START
#include"dynamics_cores.h"
#include"dynamics_diffuse.h"
#include"dynamics_mart.h"
#include"dynamics_stress.h"
#include"dynamics_xxx.h"
//GS_SYS_DEFINE_END
/////////////////////////////
#include"gs.h"
